*** Variables ***
${auditTrailTab}                        xpath://*[@id="tab_Audit Traillink"]
${selectCheckBoxAT}                     xpath://*[@class="eo_css_ctrl_ctl00_ContentPlaceHolder1_Grid12"]
${deleteAuditTrailLogConfBox}           xpath://*[@id="ctl00_ContentPlaceHolder1_lblPageHeader"]
${deleteConfOk}                         xpath://*[@id="ctl00_ContentPlaceHolder1_Dialog1_ctl01_btnConfirm"]
${deleteCancle}                         xpath://*[@id="ctl00_ContentPlaceHolder1_Dialog1_ctl01_btnCancel"]
${auditTrailDelSuccessMsg}              xpath://*[@class="jq-toast-single jq-has-icon jq-icon-success"]
${multiselectBox}                       xpath://*[@id="ctl00_ContentPlaceHolder1_Grid1_c0_i"]
${requestFilter}                        xpath://*[@id="ctl00_ContentPlaceHolder1_ddlAction"]
${severityFilter}                       xpath://*[@id="ctl00_ContentPlaceHolder1_ddlSeverity"]
${deleteCheckedItemsAT}                 xpath://*[@id="ctl00_ContentPlaceHolder1_btlDeleteCheckItems"]
${startdatepicker}                      xpath://*[@id="_eo_ctl00_ContentPlaceHolder1_dtPickerStart_picker"]
${enddatepicker}                        xpath://*[@id="_eo_ctl00_ContentPlaceHolder1_dtPickerEnd_picker"]
${checkRecordlistUpdate}                xpath://*[@id="ctl00_ContentPlaceHolder1_Grid1_i0_c0"]
${clickOnExportAuditLog}                xpath://*[@href="#"][@title="Export Audit Log"]
${dateandTimeColumn}                    xpath://*[@id="ctl00_ContentPlaceHolder1_Grid1_i0_c4"]
${deleteCurrentLogs}                    xpath://*[@href="deleteitem.aspx?Type=PartnerUserAuditDeleteCurrent"]
${deleteAllLogs}                        xpath://*[@href="deleteitem.aspx?Type=PartnerUserAuditDeleteAll"]
${cancledeleteConformBox}               xpath://*[@id="ctl00_ContentPlaceHolder1_Dialog1_ctl01_btnCancel"]
${auditTrailConfMsg}                    xpath://*[@id="ctl00_ContentPlaceHolder1_lblConfirmDelete"]
${deleteUsrMsgTxt}                      xpath://*[@id="ctl00_ContentPlaceHolder1_Dialog1_ctl00_lblMessage"]
${clickOnRefresh}                       xpath://*[@href="#"][@title="Refresh"]
${pageLocatorNo}                        xpath://*[@id="ctl00_ContentPlaceHolder1_Grid1_pr_ctl01"]
${DeleteAuditRecords}                   xpath://*[@id="ctl00_ContentPlaceHolder1_Dialog1_ctl01_btnConfirm"]
${ActionReqTWCount0}                    xpath://*[@id="ctl00_ContentPlaceHolder1_lbl2OTPAudit1"]
${SevereItmTWCount0}                    xpath://*[@id="ctl00_ContentPlaceHolder1_lbl2OTPAudit2"]
${ActionReqLWCount0}                    xpath://*[@id="ctl00_ContentPlaceHolder1_lbl2OTPAudit4"]
${SevereItmLWCount0}                    xpath://*[@id="ctl00_ContentPlaceHolder1_lbl2OTPAudit5"]
${ActionReqTMCount0}                    xpath://*[@id="ctl00_ContentPlaceHolder1_lbl2OTPAudit7"]
${SevereItmTMCount0}                    xpath://*[@id="ctl00_ContentPlaceHolder1_lbl2OTPAudit8"]
${emptyLogBtn}                          xpath://*[@id="ctl00_ContentPlaceHolder1_btnEmptyLog"]
${confirmbtn_AuditTrail}                xpath://*[@id="ctl00_ContentPlaceHolder1_Dialog1_ctl01_btnConfirm"]
${EmptyOption_AuditTrail}               xpath://*[@id="ctl00_ContentPlaceHolder1_btnEmptyLog"]
