*** Variables ***
${ManageDashboard}                  xpath://*[@id="submenu_line"]/a[5]
${MD_Authentications}               xpath://*[@id="ctl00_ContentPlaceHolder1_Grid1_i0_c0"]/div/input
${MD_AuthDaily}                     xpath://*[@id="ctl00_ContentPlaceHolder1_Grid1_i1_c0"]/div/input
${MD_AuthMonthly}                   xpath://*[@id="ctl00_ContentPlaceHolder1_Grid1_i2_c0"]/div/input
${MD_AuthWeekly}                    xpath://*[@id="ctl00_ContentPlaceHolder1_Grid1_i3_c0"]/div/input
${MD_SystemAlerts}                  xpath://*[@id="ctl00_ContentPlaceHolder1_Grid1_i4_c0"]/div/input
${MD_Tokens}                        xpath://*[@id="ctl00_ContentPlaceHolder1_Grid1_i5_c0"]/div/input
${MD_Users}                         xpath://*[@id="ctl00_ContentPlaceHolder1_Grid1_i6_c0"]/div/input
${MD_Save}                          xpath://*[@id="ctl00_ContentPlaceHolder1_btnSave"]
${MD_Close}                         xpath://*[@id="ctl00_ContentPlaceHolder1_btnClose"]
${MD_Authentications}               xpath://*[@id="ctl00_ContentPlaceHolder1_Grid1_i0_c2"]//*[@class="tabBodyCellStyle"]
${MD_AuthByDateRangeDaily}          xpath://*[@id="ctl00_ContentPlaceHolder1_Grid1_i1_c2"]//*[@class="tabBodyCellStyle"]
${MD_AuthByDateRangeMonthly}        xpath://*[@id="ctl00_ContentPlaceHolder1_Grid1_i2_c2"]//*[@class="tabBodyCellStyle"]
${MD_AuthByDateRangeWeekly}         xpath://*[@id="ctl00_ContentPlaceHolder1_Grid1_i3_c2"]//*[@class="tabBodyCellStyle"]
${MD_SystemAlerts}                  xpath://*[@id="ctl00_ContentPlaceHolder1_Grid1_i4_c2"]//*[@class="tabBodyCellStyle"]
${MD_Tokens}                        xpath://*[@id="ctl00_ContentPlaceHolder1_Grid1_i5_c2"]//*[@class="tabBodyCellStyle"]
${MD_Users}                         xpath://*[@id="ctl00_ContentPlaceHolder1_Grid1_i6_c2"]//*[@class="tabBodyCellStyle"]
${CloseButton}                      xpath://*[@id="ctl00_ContentPlaceHolder1_btnClose"]
${WelcomeMsgBar}                    xpath://*[@id="ctl00_lblErrorMsgBoxLabel0"]
${EditAccountLink}                  xpath://*[@id="ctl00_LoggedInAs"]
${ClickOnAbout}                     xpath://*[@href="about.aspx"]
${ClickOnContactSupport}            xpath://*[@href="contactsupport.aspx"]
${ProblemAreaDrpdwn}                xpath://*[@id="ctl00_ContentPlaceHolder1_ddlProblemArea"]
${AboutPageHeader}                  xpath://*[@id="ctl00_ContentPlaceHolder1_lblPageHeader"]
${LoginCredentials}                 xpath://*[@id="ctl00_ContentPlaceHolder1_lblpdivLoginCredentials"]
${ContactSupportHeading}            xpath://*[@id="ctl00_ContentPlaceHolder1_lblPageHeader"]
${ClickOnGetStarted}                xpath://*[@href="downloads.aspx"]
${GetStartedHeader}                 xpath://*[@id="ctl00_ContentPlaceHolder1_lblPageHeader"]
${ClickOnUpdate}                    xpath://*[@id="ctl00_ContentPlaceHolder1_btnSave"]
${SystemAlertsTitle}                xpath://*[@id="ctl00_ContentPlaceHolder1_SystemAlertsDashboardControl_ddlSystemAlertsChartType"]
${AuthenticationsTitle}             xpath://*[@id="ctl00_ContentPlaceHolder1_AuthenticationsDashboardControl_ddlAuthenticationsChartType"]
${TokensTitle}                      xpath://*[@id="ctl00_ContentPlaceHolder1_TokensDashboardControl_ddlTokensChartType"]
${UsersTitle}                       xpath://*[@id="ctl00_ContentPlaceHolder1_UsersDashboardControl_ddlUsersChartType"]
${TokenChartTypes}                  xpath://*[@id="ctl00_ContentPlaceHolder1_TokensDashboardControl_ddlTokensChartType"]
${AuthChartTypes}                   xpath://*[@id="ctl00_ContentPlaceHolder1_AuthenticationsDashboardControl_ddlAuthenticationsChartType"]
${TokensChartType}                  xpath://*[@name="ctl00$ContentPlaceHolder1$TokensDashboardControl$ddlTokensChartType"]
${MobileTokenStatistics}            xpath://*[@id="ctl00_ContentPlaceHolder1_TokensDashboardControl_lblMobileTokens"]
${PieChart}                         xpath://*[@d="M225,155.4L313.2747075843715,215.60538713912544A116,92.80000000000001,0,1,1,212.20551332748647,63.166206242486155L225,155.4A0,0,0,1,0,225,155.4"]
${BarChart}                         xpath://*[@height="333"]//*[text()="Enabled"]
${SystemAlertsChartTypes}           xpath://*[@id="ctl00_ContentPlaceHolder1_SystemAlertsDashboardControl_ddlSystemAlertsChartType"]
${SecurityKeyPie}                   xpath://*[@column-id="Mobile"]
${NoPortalLoginError}               xpath://*[@id="lblErrorMsgBoxLabel0"]
${UsersChartType}                   xpath://*[@id="ctl00_ContentPlaceHolder1_UsersDashboardControl_ddlUsersChartType"]
${AuthDailyHeaderTitle}             xpath://*[@id="ctl00_ContentPlaceHolder1_AuthenticationsByDateRangeDailyDashboardControl_lblChartHeader"]
${AuthMonthlyHeaderTitle}           xpath://*[@id="ctl00_ContentPlaceHolder1_AuthenticationsByDateRangeMonthlyDashboardControl_lblChartHeader"]
${AuthWeeklyHeaderTitle}            xpath://*[@id="ctl00_ContentPlaceHolder1_AuthenticationsByDateRangeWeeklyDashboardControl_lblChartHeader"]
${AuthSuccessful}                   xpath://*[text()="Successful"]

${AuthDailyStartDate}               xpath://*[@id="ctl00_ContentPlaceHolder1_AuthenticationsByDateRangeDailyDashboardControl_lblStartDate"]
${AuthDailyEndDate}                 xpath://*[@id="ctl00_ContentPlaceHolder1_AuthenticationsByDateRangeDailyDashboardControl_lblEndDate"]
${AuthStartDatePicker}              xpath://*[@id="_eo_ctl00_ContentPlaceHolder1_AuthenticationsByDateRangeDailyDashboardControl_dtPickerStart_popupimg"]
${AuthEndDatePicker}                xpath://*[@id="_eo_ctl00_ContentPlaceHolder1_AuthenticationsByDateRangeDailyDashboardControl_dtPickerEnd_popupimg"]

${AuthMonthlyStartDate}             xpath://*[@id="ctl00_ContentPlaceHolder1_AuthenticationsByDateRangeMonthlyDashboardControl_lblStartDate"]
${AuthMonthlyEndDate}               xpath://*[@id="ctl00_ContentPlaceHolder1_AuthenticationsByDateRangeMonthlyDashboardControl_lblEndDate"]
${AuthMonthlyStartDatePicker}       xpath://*[@id="_eo_ctl00_ContentPlaceHolder1_AuthenticationsByDateRangeMonthlyDashboardControl_dtPickerStart_popupimg"]
${AuthMonthlyEndDatePicker}         xpath://*[@id="_eo_ctl00_ContentPlaceHolder1_AuthenticationsByDateRangeMonthlyDashboardControl_dtPickerEnd_popupimg"]

${AuthWeeklyStartDate}              xpath://*[@id="ctl00_ContentPlaceHolder1_AuthenticationsByDateRangeWeeklyDashboardControl_lblStartDate"]
${AuthWeeklyEndDate}                xpath://*[@id="ctl00_ContentPlaceHolder1_AuthenticationsByDateRangeWeeklyDashboardControl_lblEndDate"]
${AuthWeeklyStartDatePicker}        xpath://*[@id="_eo_ctl00_ContentPlaceHolder1_AuthenticationsByDateRangeWeeklyDashboardControl_dtPickerStart_popupimg"]
${AuthWeeklyEndDatePicker}          xpath://*[@id="_eo_ctl00_ContentPlaceHolder1_AuthenticationsByDateRangeWeeklyDashboardControl_dtPickerEnd_popupimg"]

${inputStartDateAuthWeek}           xpath://*[@id="_eo_ctl00_ContentPlaceHolder1_AuthenticationsByDateRangeWeeklyDashboardControl_dtPickerStart_picker"]
${inputEndDateAuthWeek}             xpath://*[@id="_eo_ctl00_ContentPlaceHolder1_AuthenticationsByDateRangeWeeklyDashboardControl_dtPickerEnd_picker"]
${StartDateErrorMsg}                xpath://*[@class="UImessagebar UImessagebar-error UImessagebar-error"][1]
${StartDateFutureDate}              xpath://*[@class="UImessagebar UImessagebar-error UImessagebar-error"][2]

${inputStartDateAuthMonth}          xpath://*[@id="_eo_ctl00_ContentPlaceHolder1_AuthenticationsByDateRangeMonthlyDashboardControl_dtPickerStart_picker"]
${inputEndDateAuthMonth}            xpath://*[@id="_eo_ctl00_ContentPlaceHolder1_AuthenticationsByDateRangeMonthlyDashboardControl_dtPickerEnd_picker"]

${inputStartDateAuthDaily}          xpath://*[@id="_eo_ctl00_ContentPlaceHolder1_AuthenticationsByDateRangeDailyDashboardControl_dtPickerStart_picker"]
${inputEndDateAuthDaily}            xpath://*[@id="_eo_ctl00_ContentPlaceHolder1_AuthenticationsByDateRangeDailyDashboardControl_dtPickerEnd_picker"]
${FutureDateZero_0}                 xpath://*[@x="335" and  @y="140"]
${FutureDateZero_1}                 xpath://*[@x="557" and  @y="140"]
${Date1}                            xpath://*[@x="95.55507246376811"]
${Date2}                            xpath://*[@x="241.43913043478258"]
${Week1}                            xpath://*[@x="90"]                  #xpath://*[@x="144.30714285714285"]
${Week2}                            xpath://*[@x="486.6880952380953"]
${StartingZero}                     xpath://*[@x="76" and @y="287.4"]
${CheckNegativeValue}               xpath://*[@x="75" and @y="287.4"]
${RandomeClick}                     xpath:/html/body/div
${AuthDateDaily}                    xpath://*[@name="_eo_ctl00_ContentPlaceHolder1_AuthenticationsByDateRangeDailyDashboardControl_dtPickerStart_picker"]
${AssendingnDesendingbtn}           xpath://*[@id="ctl00_ContentPlaceHolder1_Grid1_c1_i"]
#####
${MD_Close}                     xpath://*[@id="ctl00_ContentPlaceHolder1_btnClose"]
${StartDateCalendarDaily}       xpath://*[@id="_eo_ctl00_ContentPlaceHolder1_AuthenticationsByDateRangeDailyDashboardControl_dtPickerStart_picker"]
${EndDateCalendarDaily}         xpath://*[@id="_eo_ctl00_ContentPlaceHolder1_AuthenticationsByDateRangeDailyDashboardControl_dtPickerEnd_picker"]
${StartDateCalendarWeekly}      xpath://*[@id="_eo_ctl00_ContentPlaceHolder1_AuthenticationsByDateRangeWeeklyDashboardControl_dtPickerStart_picker"]
${EndDateCalendarWeekly}        xpath://*[@id="_eo_ctl00_ContentPlaceHolder1_AuthenticationsByDateRangeWeeklyDashboardControl_dtPickerEnd_picker"]
${StartDateCalendarMonthly}     xpath://*[@id="_eo_ctl00_ContentPlaceHolder1_AuthenticationsByDateRangeMonthlyDashboardControl_dtPickerStart_picker"]
${EndDateCalendarMonthly}       xpath://*[@id="_eo_ctl00_ContentPlaceHolder1_AuthenticationsByDateRangeMonthlyDashboardControl_dtPickerEnd_picker"]
${NextMonth}                    xpath://*[@id="_eo_ctl00_ContentPlaceHolder1_AuthenticationsByDateRangeDailyDashboardControl_dtPickerStart_right_arrow_image"]
${FutureDate}                   xpath://*[@id="_eo_ctl00_ContentPlaceHolder1_AuthenticationsByDateRangeDailyDashboardControl_dtPickerStart_dv_0"]/tbody/tr[2]/td[4]/div
${Successful_xy}                xpath://*[@x="332.5" and @y="139.5"]
${Failed_xy}                    xpath://*[@x="554.5" and @y="139.5"]
${Date1}                        xpath://*[@x="128.08909774436088"]
${Date2}                        xpath://*[@x="290.26954887218045"]
${Date3}                        xpath://*[@x="549.7582706766918"]
${RandomeClick}                 xpath:/html/body/div
${Weekof1}                      xpath://*[@x="146.875"]
${Weekof2}                      xpath://*[@x="398.52500000000003"]
${Weekof3}                      xpath://*[@x="686.1250000000001"]
${WeekAuth1}                    xpath://*[@x="301.80238095238093"]
${WeekAuth2}                    xpath://*[@x="438.7547619047619"]
${WeekAuth3}                    xpath://*[@x="781.1357142857142"]
${AboutLnk}                     xpath://*[@title="About"]
${AboutTitle}                   xpath://*[text()="About SurePassID Corp."]
${AccountLnk}                   xpath://*[@title="Accounts"]
${ClickOnUpdateOption}          xpath://*[@id="ctl00_ContentPlaceHolder1_btnSave"]
