*** Variables ***
${OpnItmReqAct}             xpath://*[@id="ctl00_ContentPlaceHolder1_hplOTPAudit0"]
${OpnItmReqAct1}            xpath://*[@id="ctl00_ContentPlaceHolder1_hplOTPAudit0"]
${AuditTrailHeader}         xpath://*[@id="ctl00_ContentPlaceHolder1_lblPageHeader"]
${OpenSevereItems}          xpath://*[@id="ctl00_ContentPlaceHolder1_hplOTPAudit1"]
${ItmReqActThisWeek}        xpath://*[@id="ctl00_ContentPlaceHolder1_hplOTPAudit2"]
${SevereIssuesThisWeek}     xpath://*[@id="ctl00_ContentPlaceHolder1_hplOTPAudit3"]
${ItmReqActLastWeek}        xpath://*[@id="ctl00_ContentPlaceHolder1_hplOTPAudit4"]
${SevereIssuesLastWeek}     xpath://*[@id="ctl00_ContentPlaceHolder1_hplOTPAudit5"]
${ItmReqActThisMonth}       xpath://*[@id="ctl00_ContentPlaceHolder1_hplOTPAudit7"]
${SevereIssuesLastMonth}    xpath://*[@id="ctl00_ContentPlaceHolder1_hplOTPAudit8"]
${Account}                  xpath://*[@id="submenu_line"]/a[1]
${CustomizeMobileMsg}       xpath://*[@id="submenu_line"]/a[3]
${SmsProvider}              xpath://*[@id="ctl00_ContentPlaceHolder1_ddlSMSProvider"]
${UpdateBtn}                xpath://*[@id="ctl00_ContentPlaceHolder1_btnAction"]
${ClickOnLogout}            xpath://*[@id="ctl00_lnkbtnLogout"]
${SmsOtp}                   xpath://*[@id="btnSendSMSOTP"]

${ActionReqTWLBH}           xpath://*[@id="ctl00_ContentPlaceHolder1_lbl2OTPAudit1"]
${ActionReqTMLBH}           xpath://*[@id="ctl00_ContentPlaceHolder1_lbl2OTPAudit7"]
${SevereItemsTWLink}        xpath://*[@id="ctl00_ContentPlaceHolder1_lbl2OTPAudit2"]
${SevereItemsTMLink}        xpath://*[@id="ctl00_ContentPlaceHolder1_lbl2OTPAudit8"]
${ActionReqLWLBH}           xpath://*[@id="ctl00_ContentPlaceHolder1_lbl2OTPAudit4"]
${SevereItemsLWLink}        xpath://*[@id="ctl00_ContentPlaceHolder1_lbl2OTPAudit5"]
${SurePassPortalErrMsgBox}  xpath://*[@id="lblErrorMsgBoxLabel0"]
${SendVoiceOTPBtn}          xpath://*[@id="btnSendVoiceOTP"]
${SuccessCMMsg}             xpath://*[@class="jq-toast-single jq-has-icon jq-icon-success"]
