****Settings***
Resource    ../labels/SandboxDevEnvConfig.robot

*** Variables ***
${SystemAlertsPanel}              xpath://*[@id="ctl00_ContentPlaceHolder1_divSystemAlerts"]
${SysAltsGridFtm}                 xpath://*[@id="ctl00_ContentPlaceHolder1_SystemAlertsDashboardControl_divSystemAlertsClassic"]//table[@class="pageheadertable"]
${SysAltsBarFtm}                  xpath://*[@id="ctl00_ContentPlaceHolder1_SystemAlertsDashboardControl_ddlSystemAlertsChartType"]
${SysAltsBarFtmChart}             xpath://*[@id="ctl00_ContentPlaceHolder1_SystemAlertsDashboardControl_divSystemAlertsChart"]
${SysAltsThisWeek}                xpath://*[@id='ctl00_ContentPlaceHolder1_SystemAlertsDashboardControl_lblThisWeek']
${SysAltsLastWeek}                xpath://*[@id='ctl00_ContentPlaceHolder1_SystemAlertsDashboardControl_lblLastWeek']
${SysAltsThisMonth}               xpath://*[@id='ctl00_ContentPlaceHolder1_SystemAlertsDashboardControl_lblThisMonth']
${ThisWeekActionReq}              xpath://*[@id='ctl00_ContentPlaceHolder1_SystemAlertsDashboardControl_imgActionRequiredThisWeek']
${ThisWeekSevere}                 xpath://*[@id='ctl00_ContentPlaceHolder1_SystemAlertsDashboardControl_imgActionRequiredThisWeek']
${ThisWeekWarning}                xpath://*[@id='ctl00_ContentPlaceHolder1_SystemAlertsDashboardControl_imgActionRequiredThisWeek']
${ThisWeekActionReqValue}         xpath://*[@id="ctl00_ContentPlaceHolder1_SystemAlertsDashboardControl_hlActionRequiredThisWeek"]
${ThisWeekSevereValue}            xpath://*[@id="ctl00_ContentPlaceHolder1_SystemAlertsDashboardControl_hlSevereItemsThisWeek"]
${ThisWeekWarningValue}           xpath://*[@id='ctl00_ContentPlaceHolder1_SystemAlertsDashboardControl_hlWarningThisWeek']
${AuditTrailPage}                 xpath://*[text()='Audit Trail']
${LastWeekActionReqValue}         xpath://*[@id='ctl00_ContentPlaceHolder1_SystemAlertsDashboardControl_hlActionRequiredLastWeek']
${LastWeekSevereValue}            xpath://*[@id="ctl00_ContentPlaceHolder1_SystemAlertsDashboardControl_hlSevereItemsLastWeek"]
${LastWeekWarningValue}           xpath://*[@id='ctl00_ContentPlaceHolder1_SystemAlertsDashboardControl_hlWarningLastWeek']
${ThisMonthActionReqValue}        xpath://*[@id='ctl00_ContentPlaceHolder1_SystemAlertsDashboardControl_hlActionRequiredThisMonth']
${ThisMonthSevereValue}           xpath://*[@id="ctl00_ContentPlaceHolder1_SystemAlertsDashboardControl_hlSevereItemsThisMonth"]
${ThisMonthWarningValue}          xpath://*[@id='ctl00_ContentPlaceHolder1_SystemAlertsDashboardControl_hlWarningThisMonth']
${LoginUsrLogs}                   xpath://*[@id='ctl00_ContentPlaceHolder1_Grid1_i0_c3'] [normalize-space()='${UserName}']
${OPTInputTxt}                    xpath://*[@id='tbxOTP']
${OPTVerifyBtn}                   xpath://*[@id='btnVerifyOtp']
${StatusDrp}                      xpath://*[@id='ctl00_ContentPlaceHolder1_ddlDeviceStatusData']
${AdminUsrLink}                   xpath://*[@id='ctl00_LoggedInAs']
${HomePageMsg}                    xpath://*[@id="ctl00_lblErrorMsgBoxLabel0"] [text()="Hello ${inputUserName2} ${inputUserName2}. Welcome Back"]