*** Variables ***

${StatusEnabled}            xpath://*[@id="ctl00_ContentPlaceHolder1_lbl2TokenStats1"]
${StatusDisabled}           xpath://*[@id="ctl00_ContentPlaceHolder1_lbl2TokenStats2"]
${StatusNew}                xpath://*[@id="ctl00_ContentPlaceHolder1_lbl2TokenStats3"]
${TokenCount}               xpath://*[@id="ctl00_ContentPlaceHolder1_lbl2TokenStats4"]
${MobileTokens}             xpath://*[@id="ctl00_ContentPlaceHolder1_lbl2TokenStats5"]
${HardTokens}               xpath://*[@id="ctl00_ContentPlaceHolder1_lbl2TokenStats6"]
${DesktopTokens}            xpath://*[@id="ctl00_ContentPlaceHolder1_lbl2TokenStats7"]
${FidoTokens}               xpath://*[@id="ctl00_ContentPlaceHolder1_lbl2TokenStats8"]
${TknNewLink}               xpath://*[@id="ctl00_ContentPlaceHolder1_hplNew"]
${SelectTokenType}          xpath://*[@id="ctl00_ContentPlaceHolder1_ddlDevice_TypeData"]
${AssignToUserTextBox}      xpath://*[@id="ctl00_ContentPlaceHolder1_tbxAssignedUser"]
${UserDefineTokenName}      xpath://*[@id="ctl00_ContentPlaceHolder1_tbxToken_Alias"]
${TokenAddButton}           xpath://*[@id="ctl00_ContentPlaceHolder1_btnAction"]
${FilterUser}               xpath://*[@id="ctl00_ContentPlaceHolder1_ddlFilterComparator"]
${EditLinkUser}             xpath://*[text()= "${UserName}"]/parent::div//parent::div//*[@src="images/icons-mini/edit.png"]
${SearialNumberCol}         xpath://*[@id="ctl00_ContentPlaceHolder1_Grid1_c2_i"]
${SearialNumber}            xpath://*[@id="ctl00_ContentPlaceHolder1_tbxPrinted_Serial_NumberData"]
${DeleteLinkToken}          xpath://*[text()= "${DemoTokenName}"]/parent::div//parent::div//*[@src="images/icons-mini/trash_black_white.png"]
${DeleteToken}              xpath://*[@id="ctl00_ContentPlaceHolder1_Dialog1_ctl01_btnConfirm"]
${SrNumSearchTextBox}       xpath://*[@id="ctl00_ContentPlaceHolder1_tbxSerialNumber"]
${TokenStatusType}          xpath://*[@id="ctl00_ContentPlaceHolder1_ddlDeviceStatusData"]
${ImportHardTokenLink}      xpath://*[@id="submenu_line"]/a[2]
${NextButton}               xpath://*[@id="ctl00_ContentPlaceHolder1_btnAction"]
${MapDataColOne}            xpath://*[@id="ctl00_ContentPlaceHolder1_ddl0"]
${MapDataColTwo}            xpath://*[@id="ctl00_ContentPlaceHolder1_ddl1"]
${NotesImportHrdTkn}        xpath://*[@id="ctl00_ContentPlaceHolder1_tbxAddtionalComments"]
${SelectFilterTokenType}    xpath://*[@id="ctl00_ContentPlaceHolder1_ddlType"]
${clickonusertab}           xpath://*[@id="tab_Userslink"]
${DeleteHardToken}          xpath://*[text()= "SurePassID FOB Token"]/parent::div//parent::div//*[@src="images/icons-mini/trash_black_white.png"]
