*** Variables ***
${TokenPageHeader}              xpath://*[@id="ctl00_ContentPlaceHolder1_lblPageHeader"]
${TokenTypeDropdown}            xpath://*[text()="Token Type:"]//parent::td//following-sibling::*//select
${UserDefinedNameField}         xpath://*[@id="ctl00_ContentPlaceHolder1_tbxToken_Alias"]
${TokenAddButton}               xpath://*[@id="ctl00_ContentPlaceHolder1_btnAction"]
${SerialNoFilterDropdown}       xpath://*[@id="ctl00_ContentPlaceHolder1_ddlSerialNumberFilterComparator"]
${SrNoFilterSearchField}        xpath://*[@id="ctl00_ContentPlaceHolder1_tbxSerialNumber"]
${SrNoFilterSearchIcon}         xpath://*[@id="ctl00_ContentPlaceHolder1_btnFindSerial"]
${TokenPageDeleteAction}        xpath://*[text()= "${UDNTokenName}"]/parent::div//parent::div//*[@src="images/icons-mini/trash_black_white.png"]
#${TokenPageEditAction}          xpath://*[text()= "${UDNTokenName}"]/parent::div//parent::div//*[@src="images/icons-mini/edit.png"]
${TokenPageEditAction}          xpath://*[@id="ctl00_ContentPlaceHolder1_Grid1_i0_c1"]/div/a[1]
${TokenPageEditCompare}         xpath://*[text()= "${TokenDefName}"]/parent::div//parent::div//*[@src="images/icons-mini/edit.png"]
${TokenPageEditActionRename}    xpath://*[text()= "${UDNTokenName}"]/parent::div//parent::div//*[@src="images/icons-mini/edit.png"]
${CrossIcon}                    xpath://*[@id="ctl00_ContentPlaceHolder1_iconurl"]
${DeleteButton}                 xpath://*[@id="ctl00_ContentPlaceHolder1_Dialog1_ctl01_btnConfirm"]
${TokenDeleteSuccessMsg}        xpath://*[text()="Token(s) deleted from the system."]
${TokenNameEditField}           xpath://*[@id="ctl00_ContentPlaceHolder1_tbxToken_Alias"]
${TokenEditUpdateLink}          xpath://*[@id="ctl00_ContentPlaceHolder1_btlSave"]
${TokenUpdatedPopup}            xpath://*[text()="Record has been updated."]
${TokenUpdateUser}              xpath://*[@name="ctl00$ContentPlaceHolder1$tbxAssignedUser"]
${TokenStatusDropdown}          xpath://*[@id="ctl00_ContentPlaceHolder1_ddlDeviceStatusData"]
${TokenEditSrNoField}           xpath://*[@id="ctl00_ContentPlaceHolder1_tbxPrinted_Serial_NumberData"]
${TokenID}                      xpath://*[@id="ctl00_ContentPlaceHolder1_tbxUnique_IdentifierData"]
${InstantActivationIcon}        xpath://*[@name="ctl00$ContentPlaceHolder1$btnShowInstantActivation"]
${ActivationText}               xpath://*[@id="ctl00_ContentPlaceHolder1_lblInstantActivationLink"]
${OTPLengthSelected}            xpath://*[@id="ctl00_ContentPlaceHolder1_ddlOTP_LengthData"]//*[@selected="selected"]
${OTPTypeDropdown}              xpath://*[@id="ctl00_ContentPlaceHolder1_ddlOTP_TypeData"]
${PINTextfieldLocator}          xpath://*[@id="ctl00_ContentPlaceHolder1_tbxPINData"]
${TokenStatusLocator}           xpath://*[@id="ctl00_ContentPlaceHolder1_ddlDeviceStatusData"]
${OTPLength}                    xpath://*[@id="ctl00_ContentPlaceHolder1_ddlOTP_LengthData"]
${EditUDF}                      xpath://*[text()= "${TokenDefName}"]/parent::div//parent::div//*[@src="images/icons-mini/edit.png"]

### Assign Token Page ###
${AssignTokenLink}              xpath://*[@id="ctl00_ContentPlaceHolder1_hplAssignDevices"]
${AssignTokenSrNo}              xpath://*[@id="ctl00_ContentPlaceHolder1_tbxPrinted_Serial_NumberData"]
${AllowReassignCheckbox}        xpath://*[@id="ctl00_ContentPlaceHolder1_chkAllowReassignment"]
${EmailUserCheckbox}            xpath://*[@id="ctl00_ContentPlaceHolder1_chkEmailTokenActivation"]
${AssignTokenBtn}               xpath://*[@id="ctl00_ContentPlaceHolder1_btnAction"]
${AssignTokenUsrDropdown}       xpath://*[@id="ctl00_ContentPlaceHolder1_tbxAssignedUser"]
${devicestatusdata}             xpath://*[@id="ctl00_ContentPlaceHolder1_ddlDeviceStatusData"]
${UpdateIcon}                   xpath://*[@id="ctl00_ContentPlaceHolder1_imgUpdateProgress"]
${TokenStatusEnabled}           xpath://*[@id="ctl00_ContentPlaceHolder1_chkEnableDevice"]

#===================================
${ToastSuccess}                 xpath://*[@class="jq-toast-heading"]
${PopupDeletebutton}            xpath://*[@id="ctl00_ContentPlaceHolder1_Dialog1_ctl01_btnConfirm"]
#============================================================================
${clickOnTokens}                xpath://*[@id="tab_Tokenslink"]
${AddToken}                     xpath://*[@id="ctl00_ContentPlaceHolder1_btlSave"]
${TokenType}                    xpath://*[@id="ctl00_ContentPlaceHolder1_ddlDevice_TypeData"]
${SerialNumber}                 xpath://*[@id="ctl00_ContentPlaceHolder1_tbxPrinted_Serial_NumberData"]
${Update}                       xpath://*[@id="ctl00_ContentPlaceHolder1_btlSave"]
${Close}                        xpath://*[@id="ctl00_ContentPlaceHolder1_btlClose"]
${Cancel}                       xpath://*[@id="ctl00_ContentPlaceHolder1_Dialog1_ctl01_btnCancel"]
${SerialNumberSort}             xpath://*[@id="ctl00_ContentPlaceHolder1_Grid1_c1_i"]
${SerialFilterNumber}           xpath://*[@id="ctl00_ContentPlaceHolder1_ddlSerialNumberFilterComparator"]
${SerialFilterText}             xpath://*[@id="ctl00_ContentPlaceHolder1_tbxSerialNumber"]
${FindSerial}                   xpath://*[@id="ctl00_ContentPlaceHolder1_btnFindSerial"]
${CreateTempPwd}                xpath://*[@id="ctl00_ContentPlaceHolder1_btnTempPassword"]
${CreateTempPwdAction}          xpath://*[@id="ctl00_ContentPlaceHolder1_btnAction"]
${CreateTempPwdMsg}             xpath://*[@class="jq-toast-heading"]
${ToastPwdMsg}                  xpath://*[@class="jq-toast-wrap"]
${CloseTempPwd}                 xpath://*[@id="ctl00_ContentPlaceHolder1_btnActionClose"]
${CheckOTP}                     xpath://*[@id="ctl00_ContentPlaceHolder1_btnCheckOTP"]
${OTPField}                     xpath://*[@id="ctl00_ContentPlaceHolder1_tbxOTP"]
${CheckOTPAction}               xpath://*[@id="ctl00_ContentPlaceHolder1_btnAction"]
${CheckOTPMessage}              xpath://*[@id="ctl00_lblErrorMsgBoxLabel0"]
${SuccessMsgLocator}            xpath://*[@class="jq-toast-heading"]
${SuccessMsgLocatorShare}       xpath://*[@id="ctl00_ContentPlaceHolder1_lblErrorMsgBoxLabel0"]
${CheckAssignmentBtn}           xpath://*[@id="ctl00_ContentPlaceHolder1_btnCheck"]
${CloseSuccessMsg}              xpath://*[@id="ctl00_ContentPlaceHolder1_Dialog1_ctl01_btnCancel"]
${AuthUsageDropdown}            xpath://*[@id="ctl00_ContentPlaceHolder1_ddlDevice_TypeData"]
#${AuthUsageDropdown}             xpath=//*[@id="ctl00_ContentPlaceHolder1_ucMobileUsage_cbOath"]
${OTPWindowSizeLocator}         xpath://*[@id="ctl00_ContentPlaceHolder1_tbxOTP_Window_SizeData"]
${ResetToken}                   xpath://*[@id="ctl00_ContentPlaceHolder1_btlResetToken"]

##===============================Token Listing Page=============================================
${ActionHeaderLocator}           xpath://*[@id="ctl00_ContentPlaceHolder1_Grid1_c1_i"]
${SNHeaderLocator}               xpath://*[@id="ctl00_ContentPlaceHolder1_Grid1_c2_i"]
${UserDefHeaderLocator}          xpath://*[@id="ctl00_ContentPlaceHolder1_Grid1_c3_i"]
${StatusHeaderLocator}           xpath://*[@id="ctl00_ContentPlaceHolder1_Grid1_c4_i"]
${TokenTypeHeaderLocator}        xpath://*[@id="ctl00_ContentPlaceHolder1_Grid1_c5_i"]
${LastOTPHeaderLocator}          xpath://*[@id="ctl00_ContentPlaceHolder1_Grid1_c7_i"]
${OTPTypeHeaderLocator}          xpath://*[@id="ctl00_ContentPlaceHolder1_Grid1_c9_i"]
${DigitsHeaderLocator}           xpath://*[@id="ctl00_ContentPlaceHolder1_Grid1_c10_i"]
${EditLinkLocator}               xpath://parent::div//parent::div//*[@src="images/icons-mini/edit.png"]
${DeleteLinkLocator}             xpath://parent::div//parent::div//*[@src="images/icons-mini/trash_black_white.png"]

##===============================Token Filters =============================================
${TokenTypeFilter}               xpath://*[@id="ctl00_ContentPlaceHolder1_ddlType"]
${UserAssignmentFilter}          xpath://*[@id="ctl00_ContentPlaceHolder1_ddlStatus"]
${DeviceStatusFilter}            xpath://*[@id="ctl00_ContentPlaceHolder1_ddlDeviceStatus"]
${DisplayRecordsFilter}          xpath://*[@id="ctl00_ContentPlaceHolder1_ddlPageSize"]
${UserTokenFilter}               xpath://*[@id="ctl00_ContentPlaceHolder1_ddlUserFilterComparator"]
${UserTokenInputField}           xpath://*[@id="ctl00_ContentPlaceHolder1_tbxAssignedUser"]
${UserTokenSearchBtn}            xpath://*[@id="ctl00_ContentPlaceHolder1_btnFindUser"]
${PageCountLocator}              xpath://*[@id="ctl00_ContentPlaceHolder1_Grid1_pr_ctl01"]


${ShareTokenLocator}             xpath://*[@id="ctl00_ContentPlaceHolder1_btlDuplicate"]
${AssigneeDropdownLocator}       xpath://*[@id="ctl00_ContentPlaceHolder1_ddlAssigned_Partner_User_IdData"]
${ShareButtonLocator}            xpath://*[@id="ctl00_ContentPlaceHolder1_btnAction"]




##=============================== Create Temporary Password ==================================
${CreateTempPwBtn}               xpath://*[@id="ctl00_ContentPlaceHolder1_btnTempPassword"]
${CreatePwBtn}                   xpath://*[@id="ctl00_ContentPlaceHolder1_btnAction"]

##============================== Share Token ===================================================
${ShareTokenLink}                xpath://*[@id="ctl00_ContentPlaceHolder1_btlDuplicate"]
${ShareTokenSearchBox}           xpath://*[@id="ctl00_ContentPlaceHolder1_tbxUserFilter"]
${ShareTokenSearchIcon}          xpath://*[@id="ctl00_ContentPlaceHolder1_btnFilterUsers"]
${ShareTokenUserDropDwn}         xpath://*[@id="ctl00_ContentPlaceHolder1_ddlAssigned_Partner_User_IdData"]
${ShareTokenShareBtn}            xpath://*[@id="ctl00_ContentPlaceHolder1_btnAction"]

##================================ Synchronize ======================================================
${SynchronizeBtn}               xpath://*[@id="ctl00_ContentPlaceHolder1_btnResynch"]
${SyncOTPBox}                   xpath://*[@id="ctl00_ContentPlaceHolder1_tbxOTP"]
${SyncConfirm}                  xpath://*[@id="ctl00_ContentPlaceHolder1_btnAction"]
${SuccessMsg}                   xpath://*[@id="ctl00_ContentPlaceHolder1_lblErrorMsgBoxLabel0"]
${QRCode}                       xpath://*[@id="ctl00_ContentPlaceHolder1_btnImageShowQRCode"]
${ImageQRCode}                  xpath://*[@id="ctl00_ContentPlaceHolder1_ImgQRCode"]
${UDTNMessagebox}               xpath://*[@id="ctl00_ContentPlaceHolder1_lblErrorMsgBoxLabel1"]
${MobileSetupVerification}      xpath://*[@id="ctl00_ContentPlaceHolder1_ddlPushAuth"]
${TimeWindow}                   xpath://*[@id="ctl00_ContentPlaceHolder1_tbxWindowSize"]

${AccountDropdown}              xpath://*[@name="ctl00$ContentPlaceHolder1$ddlClient"]

